IF
	Global("CopperGuards","GLOBAL",1)
THEN
	RESPONSE #100
		CreateCreature("ccguard1",[1306.617],14) // Copper Coronet Guard
		CreateCreature("ccguard2",[1074.781],14) // Copper Coronet Guard
		CreateCreature("ccguard1",[1323.1341],6) // Copper Coronet Guard
		CreateCreature("ccguard2",[2832.728],6) // Copper Coronet Guard
		CreateCreature("ccguard1",[2702.644],14) // Copper Coronet Guard
		CreateCreature("ccguard2",[2303.390],6) // Copper Coronet Guard
		SetGlobal("CopperGuards","GLOBAL",2)
END
