IF
	Global("MoreGuards","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreature("slguard2",[591.1642],6) // Slaver Guard
		CreateCreature("slguard1",[710.1709],0) // Slaver Guard
		CreateCreature("slguard2",[1873.1234],14) // Slaver Guard
		CreateCreature("slguard1",[1951.1324],0) // Slaver Guard
		CreateCreature("icyuan01",[1534.369],0) // Yuan-Ti  - Yuan-Ti
		CreateCreature("icyuan01",[1295.632],0) // Yuan-Ti  - Yuan-Ti
		CreateCreature("icyuan01",[1626.408],0) // Yuan-Ti  - Yuan-Ti
		SetGlobal("MoreGuards","MYAREA",1)
END
