IF
	Global("DoSSpawn","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreature("CMAPOCAL",[359.1618],0) // 
		CreateCreature("CMAPOCAL",[206.1610],0) // 
		CreateCreature("CMAPOCAL",[726.1364],0) // 
		CreateCreature("CMAPOCAL",[1005.1974],0) // 
		CreateCreature("CMAPOCAL",[970.2429],0) // 
		ActionOverride("Vase 3",CreateItem("CMAR01",40,0,0)) //
		ActionOverride("Vase 5",CreateItem("cmrigr06",1,0,0)) //
		SetGlobal("DoSSpawn","MYAREA",1)
END
