IF
	Global("DoSSpawn","MYAREA",0)
THEN
	RESPONSE #100
		CreateCreature("CMGHOST1",[1334.1314],0) // 
		CreateCreature("CMGHOST2",[1087.1971],0) // 
		CreateCreature("CMGHOST3",[1190.541],0) // 
		SetGlobal("DoSSpawn","MYAREA",1)
END

IF
  Exists("CMGHOST1")
  TimeGT(DAWN_START)
  IsActive("CMGHOST1")
THEN
  RESPONSE #100
    Deactivate("CMGHOST1")
END

IF
  Exists("CMGHOST2")
  TimeGT(DAWN_START)
  IsActive("CMGHOST2")
THEN
  RESPONSE #100
    Deactivate("CMGHOST2")
END

IF
  Exists("CMGHOST3")
  TimeGT(DAWN_START)
  IsActive("CMGHOST3")
THEN
  RESPONSE #100
    Deactivate("CMGHOST3")
END

IF
  Exists("CMGHOST1")
  TimeGT(DUSK_START)
  !IsActive("CMGHOST1")
THEN
  RESPONSE #100
    Activate("CMGHOST1")
END

IF
  Exists("CMGHOST2")
  TimeGT(DUSK_START)
  !IsActive("CMGHOST2")
THEN
  RESPONSE #100
    Activate("CMGHOST2")
END

IF
  Exists("CMGHOST3")
  TimeGT(DUSK_START)
  !IsActive("CMGHOST3")
THEN
  RESPONSE #100
    Activate("CMGHOST3")
END


