// CM_Callisto_Armor

IF
	!InPartyAllowDead(Myself)
	Die()
THEN
	RESPONSE #100
		CreateCreatureObject("CM_SPY2",Myself,0,0,0)
		CreateCreatureObjectOffset("CM_SPY",Myself,[0.-5])
		Continue()
END

IF
	!Global("CM_Callisto_Armor","LOCALS",0)
	HasItem("CMTUPL01",Myself)
THEN
	RESPONSE #100
		SetGlobal("CM_Callisto_Armor","LOCALS",0)
		Continue()
END

IF
	!Dead("callisto")
	!InventoryFull(Myself)
	!HasItem("CMTUPL01",Myself)
	TriggerOverride(Player1,HasItem("CMTUPL01",Player1))
THEN
	RESPONSE #100
		CreateVisualEffectObject("CMARMO",Player1)
		TakePartyItem("CMTUPL01")
		CreateVisualEffectObject("CMARMO",Myself)
		ApplyDamage(Player1,4,STUNNING)
		PickUpItem("CMTUPL01")
		SetGlobal("CM_Callisto_Armor","LOCALS",1)
		Continue()
END

IF
	!Dead("callisto")
	!InventoryFull(Myself)
	!HasItem("CMTUPL01",Myself)
	TriggerOverride(Player2,HasItem("CMTUPL01",Player2))
THEN
	RESPONSE #100
		CreateVisualEffectObject("CMARMO",Player2)
		TakePartyItem("CMTUPL01")
		CreateVisualEffectObject("CMARMO",Myself)
		ApplyDamage(Player2,4,STUNNING)
		PickUpItem("CMTUPL01")
		SetGlobal("CM_Callisto_Armor","LOCALS",1)
		Continue()
END

IF
	!Dead("callisto")
	!InventoryFull(Myself)
	!HasItem("CMTUPL01",Myself)
	TriggerOverride(Player3,HasItem("CMTUPL01",Player3))
THEN
	RESPONSE #100
		CreateVisualEffectObject("CMARMO",Player3)
		TakePartyItem("CMTUPL01")
		CreateVisualEffectObject("CMARMO",Myself)
		ApplyDamage(Player3,4,STUNNING)
		PickUpItem("CMTUPL01")
		SetGlobal("CM_Callisto_Armor","LOCALS",1)
		Continue()
END

IF
	!Dead("callisto")
	!InventoryFull(Myself)
	!HasItem("CMTUPL01",Myself)
	TriggerOverride(Player4,HasItem("CMTUPL01",Player4))
THEN
	RESPONSE #100
		CreateVisualEffectObject("CMARMO",Player4)
		TakePartyItem("CMTUPL01")
		CreateVisualEffectObject("CMARMO",Myself)
		ApplyDamage(Player4,4,STUNNING)
		PickUpItem("CMTUPL01")
		SetGlobal("CM_Callisto_Armor","LOCALS",1)
		Continue()
END

IF
	!Dead("callisto")
	!InventoryFull(Myself)
	!HasItem("CMTUPL01",Myself)
	TriggerOverride(Player5,HasItem("CMTUPL01",Player5))
THEN
	RESPONSE #100
		CreateVisualEffectObject("CMARMO",Player5)
		TakePartyItem("CMTUPL01")
		CreateVisualEffectObject("CMARMO",Myself)
		ApplyDamage(Player5,4,STUNNING)
		PickUpItem("CMTUPL01")
		SetGlobal("CM_Callisto_Armor","LOCALS",1)
		Continue()
END

IF
	!Dead("callisto")
	!InventoryFull(Myself)
	!HasItem("CMTUPL01",Myself)
	TriggerOverride(Player6,HasItem("CMTUPL01",Player6))
THEN
	RESPONSE #100
		CreateVisualEffectObject("CMARMO",Player6)
		TakePartyItem("CMTUPL01")
		CreateVisualEffectObject("CMARMO",Myself)
		ApplyDamage(Player6,4,STUNNING)
		PickUpItem("CMTUPL01")
		SetGlobal("CM_Callisto_Armor","LOCALS",1)
		Continue()
END

IF
	Global("CM_Callisto_Armor","LOCALS",0)
	!Dead("callisto")
	!HasItem("CMTUPL01",Myself)
THEN
	RESPONSE #100
		PickUpItem("CMTUPL01")
		SetGlobal("CM_Callisto_Armor","LOCALS",1)
		Continue()
END

IF
	Global("CM_Callisto_Armor","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("CM_Callisto_Armor","LOCALS",2)
		DisplayStringHead(Myself,~It's mine, don't put your hand on it !~)
		Continue()
END

IF
	!Dead("callisto")
	!HasItem("CMTUPL01",Myself)
	!PartyHasItem("CMTUPL01")
	InParty(Myself)
	InventoryFull(Myself)
THEN
	RESPONSE #100
		ActionOverride([PC],PickUpItem("CMTUPL01"))
		DisplayStringHead(Myself,~Carry it for me, I'll take it back as soon as I can.~)
		Continue()
END

// CM_Callisto_Sword

IF
	!Global("CM_Callisto_Sword","LOCALS",0)
	InPartyAllowDead(Myself)
	OR(2)
		HasItem("CMTUSW01",Myself)
		PartyHasItem("CMTUSW01")
THEN
	RESPONSE #100
		SetGlobal("CM_Callisto_Sword","LOCALS",0)
		Continue()
END

IF
	Global("CM_Callisto_Sword","LOCALS",0)
	!Dead("callisto")
	!InParty(Myself)
	!HasItem("CMTUSW01",Myself)
	PartyHasItem("CMTUSW01")
THEN
	RESPONSE #100
		TakePartyItem("CMTUSW01")
		SetGlobal("CM_Callisto_Sword","LOCALS",1)
		Continue()
END

IF
	Global("CM_Callisto_Sword","LOCALS",0)
	!Dead("callisto")
	!HasItem("CMTUSW01",Myself)
	!PartyHasItem("CMTUSW01")
THEN
	RESPONSE #100
		PickUpItem("CMTUSW01")
		SetGlobal("CM_Callisto_Sword","LOCALS",1)
		Continue()
END

IF
	Global("CM_Callisto_Sword","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("CM_Callisto_Sword","LOCALS",2)
		DisplayStringHead(Myself,~It's mine, I don't leave it behind !~)
		Continue()
END

IF
	!Dead("callisto")
	!HasItem("CMTUSW01",Myself)
	!PartyHasItem("CMTUSW01")
	InventoryFull(Myself)
THEN
	RESPONSE #100
		ActionOverride([PC],PickUpItem("CMTUSW01"))
		DisplayStringHead(Myself,~Carry it for me.~)
		Continue()
END

// Start

IF
	NumTimesTalkedTo(0)
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	See(Player1)
THEN
	RESPONSE #100
		Dialogue(Player1)
END


// Leaving AR0700

IF
	!AreaCheck("AR0700")
	Global("CallistoJoinTalk","GLOBAL",0) // LOCALS also in CMCALLIJ.D
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(Player1)
THEN
	RESPONSE #100
		SetGlobal("CallistoJoinTalk","GLOBAL",1)
END

IF
	Global("CallistoJoinTalk","GLOBAL",1) // LOCALS also in CMCALLIJ.D
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(Player1)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1) //  From Interact
	
END


// First friend talk
IF 
	InParty(Myself)
	Global("CallistoTalk","GLOBAL",0) // LOCALS also in CMCALLIJ.D
THEN
	RESPONSE #100
		RealSetGlobalTimer("CallistoTalkTimer","GLOBAL",2000) // LOCALS also in CMCALLIJ.D
		SetGlobal("CallistoTalk","GLOBAL",1)
END

// Friend talks, sequential

IF
	RealGlobalTimerExpired("CallistoTalkTimer","GLOBAL")
	OR(9)
		Global("CallistoTalk","GLOBAL",1)
		Global("CallistoTalk","GLOBAL",3)
		Global("CallistoTalk","GLOBAL",5)
		Global("CallistoTalk","GLOBAL",7)
		Global("CallistoTalk","GLOBAL",9)
		Global("CallistoTalk","GLOBAL",11)
		Global("CallistoTalk","GLOBAL",13)
		Global("CallistoTalk","GLOBAL",15)
		Global("CallistoTalk","GLOBAL",17)
	ActionListEmpty()
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(Player1)
THEN
	RESPONSE #100
		IncrementGlobal("CallistoTalk","GLOBAL",1)
		SetGlobal("CallistoTalkCheck","GLOBAL",1) // LOCALS also in CMCALLIJ.D
//		Interact(Player1) // StartDialogNoSet // Should be only in next block
END

IF
	Global("CallistoTalkCheck","GLOBAL",1)
	!AreaType(DUNGEON)
	OR(9)
		Global("CallistoTalk","GLOBAL",2)
		Global("CallistoTalk","GLOBAL",4)
		Global("CallistoTalk","GLOBAL",6)
		Global("CallistoTalk","GLOBAL",8)
		Global("CallistoTalk","GLOBAL",10)
		Global("CallistoTalk","GLOBAL",12)
		Global("CallistoTalk","GLOBAL",14)
		Global("CallistoTalk","GLOBAL",16)
		Global("CallistoTalk","GLOBAL",18)
	ActionListEmpty()
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(Player1)
THEN
	RESPONSE #100
		SetGlobalTimer("CallistoTalkTimer","GLOBAL",3600) // Duplicated by RealSetGlobalTimer("CallistoTalkTimer","GLOBAL",3600) in CMCALLIJ.D
		StartDialogNoSet(Player1) //  From Interact
END

IF
	AreaCheck("AR0502")
	Global("TannerWarning2","AR0502",0) // LOCALS
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		SetGlobal("TannerWarning2","AR0502",1)
		StartDialogueNoSet(Player1)
END

IF
	AreaCheck("AR1602")
	!Dead("cmninaf") // !InPartyAllowDead("cmninaf")
	Global("BCalliNina3","GLOBAL",0) // Need to be GLOBAL
	!ActuallyInCombat()
	!See([ENEMY])
	InParty("cmninaf")
	!StateCheck("cmninaf",CD_STATE_NOTVALID)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See("cmninaf")
THEN
	RESPONSE #100
		Interact("cmninaf")
END

IF
	AreaCheck("AR2600")
	InParty(Myself)
	Global("CmCalliEndGameS","AR2600",0) // LOCALS also in CMCALLIJ.D
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END

IF
	Allegiance(Myself,ENEMY)
	!InParty(Myself)
	Global("NPCFight","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("NPCFight","LOCALS",1)
		ChangeAIScript("callix",SPECIFICS)
		ChangeAIScript("",GENERAL)
		ChangeAIScript("",DEFAULT)
		SetDialog("")
		Continue()
END

IF
	Allegiance(Myself,NEUTRAL)
	AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		ChangeAIScript("callix",SPECIFICS)
		ChangeAIScript("",GENERAL)
		Enemy()
		Continue()
END

IF
	!Allegiance(Myself,ENEMY)
	!InParty(Myself)
	Global("NPCFight","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("NPCFight","LOCALS",0)
		ChangeAIScript("",GENERAL)
		ChangeAIScript("",SPECIFICS)
		Continue()
END
