IF
	Global("CmCalliNinafer1","GLOBAL",0)
	Detect("cmninaf")
	InParty("cmninaf")
THEN
	RESPONSE #100
		Dialogue("cmninaf")
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		SetGlobal("CmAvat1Attack","GLOBAL",1)
		Enemy()
END

IF
	Global("CmAvat1Attack","GLOBAL",1)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END


IF
	See(NearestEnemyOf(Myself))
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	HaveSpell(HARPER_DEATH_SONG)
THEN
	RESPONSE #30
		Spell(NearestEnemyOf(Myself),HARPER_DEATH_SONG)
		Continue()
	RESPONSE #70
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	Global("CmIdiotAttacks","LOCALS",0)
THEN
	RESPONSE #100
		ReallyForceSpell(NearestEnemyOf(Myself),BANSHEE_WAIL)
		SetGlobal("CmIdiotAttacks","LOCALS",1)
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),5)
END