// CM_Ninafer_Sword

IF
	!Global("CM_Ninafer_Sword","LOCALS",0)
	InPartyAllowDead(Myself)
	OR(2)
		HasItem("CMNINASW",Myself)
		PartyHasItem("CMNINASW")
THEN
	RESPONSE #100
		SetGlobal("CM_Ninafer_Sword","LOCALS",0)
		Continue()
END

IF
	Global("CM_Ninafer_Sword","LOCALS",0)
	!Dead("cmninaf")
	!InParty(Myself)
	!HasItem("CMNINASW",Myself)
	PartyHasItem("CMNINASW")
THEN
	RESPONSE #100
		TakePartyItem("CMNINASW")
		SetGlobal("CM_Ninafer_Sword","LOCALS",1)
		Continue()
END

IF
	Global("CM_Ninafer_Sword","LOCALS",0)
	!Dead("cmninaf")
	!HasItem("CMNINASW",Myself)
	!PartyHasItem("CMNINASW")
THEN
	RESPONSE #100
		PickUpItem("CMNINASW")
		SetGlobal("CM_Ninafer_Sword","LOCALS",1)
		Continue()
END

IF
	Global("CM_Ninafer_Sword","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("CM_Ninafer_Sword","LOCALS",2)
		DisplayStringHead(Myself,~It's mine, I don't leave it behind !~)
		Continue()
END

IF
	!Dead("cmninaf")
	!HasItem("CMNINASW",Myself)
	!PartyHasItem("CMNINASW")
	InventoryFull(Myself)
THEN
	RESPONSE #100
		ActionOverride([PC],PickUpItem("CMNINASW"))
		DisplayStringHead(Myself,~Carry it for me~)
		Continue()
END

// Start

IF
	Global("FoundThievesC","GLOBAL",1)
//	Global("CM_MystraQuest","GLOBAL",0) // Useless
	Dead("cmlillian")
	PartyHasItem("CMBOOK99") // Tome of Magical Spells
	!StateCheck(Player1,CD_STATE_NOTVALID)
	InParty(Myself)
    !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1) //  From Interact
END

// Tanner warning

IF
	Global("Nina_EnteredTanner2","AR0502",0) //  From TannerWarning2
	InParty(Myself)
    !StateCheck(Myself,CD_STATE_NOTVALID)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END

// First friend talk

IF 
	InParty(Myself)
	Global("CM_NinaferTalk","GLOBAL",0)
THEN
	RESPONSE #100
		RealSetGlobalTimer("CM_NinaferTalkTimer","GLOBAL",2000)
		SetGlobal("CM_NinaferTalk","GLOBAL",1)
END

// Friend talks, sequential

IF
	RealGlobalTimerExpired("CM_NinaferTalkTimer","GLOBAL")
	OR(5)
		Global("CM_NinaferTalk","GLOBAL",1)
		Global("CM_NinaferTalk","GLOBAL",3)
		Global("CM_NinaferTalk","GLOBAL",5)
		Global("CM_NinaferTalk","GLOBAL",7)
		Global("CM_NinaferTalk","GLOBAL",9)
	ActionListEmpty()
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(Player1)
THEN
	RESPONSE #100
		IncrementGlobal("CM_NinaferTalk","GLOBAL",1)
		SetGlobal("CM_NinaferTalkCheck","GLOBAL",1)
//		Interact(Player1) // StartDialogNoSet // Should be only in next block
END

IF
	Global("CM_NinaferTalkCheck","GLOBAL",1)
	!AreaType(DUNGEON)
	OR(5)
		Global("CM_NinaferTalk","GLOBAL",2)
		Global("CM_NinaferTalk","GLOBAL",4)
		Global("CM_NinaferTalk","GLOBAL",6)
		Global("CM_NinaferTalk","GLOBAL",8)
		Global("CM_NinaferTalk","GLOBAL",10)
	ActionListEmpty()
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(Player1)
THEN
	RESPONSE #100
		SetGlobalTimer("CM_NinaferTalkTimer","GLOBAL",3600) // Duplicated by RealSetGlobalTimer("CallistoTalkTimer","GLOBAL",3600) in CMCALLIJ.D
		StartDialogNoSet(Player1) //  From Interact
END

// Anomen and Ninafer scripting

// Anomen is a knight first check
IF
	Global("AnomenIsKnight","GLOBAL",1)
	Global("CmT_NinaAnomenKnightTalk","GLOBAL",0)
	InParty(Myself)
	InParty("Anomen")
THEN
	RESPONSE #100
		RealSetGlobalTimer("CmT_NinaAnomenKnightTalkTimer","GLOBAL",300)
		SetGlobal("CmT_NinaAnomenKnightTalk","GLOBAL",1)
END

IF
	RealGlobalTimerExpired("CmT_NinaAnomenKnightTalkTimer","GLOBAL")
	Global("CmT_NinaAnomenKnightTalk","GLOBAL",1)
	ActionListEmpty()
	!ActuallyInCombat()
	!Detect([ENEMY])
	InParty("Anomen")
	!StateCheck("Anomen",CD_STATE_NOTVALID)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See("Anomen")
THEN
	RESPONSE #100
		SetGlobal("CmT_NinaAnomenKnightTalk","GLOBAL",2)
END

IF
	RealGlobalTimerExpired("CmT_NinaAnomenKnightTalkTimer","GLOBAL")
	Global("CmT_NinaAnomenKnightTalk","GLOBAL",2)
	ActionListEmpty()
	!ActuallyInCombat()
	!Detect([ENEMY])
	InParty("Anomen")
	!StateCheck("Anomen",CD_STATE_NOTVALID)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See("Anomen")
THEN
	RESPONSE #100
		MoveToObject("Anomen")
		Interact("Anomen")
END

// Ninafer official flirting

IF
	Global("CmT_NinaAnomenFlirtTalk","GLOBAL",3)
	InParty(Myself)
	InParty("Anomen")
THEN
	RESPONSE #100
		RealSetGlobalTimer("CmT_NinaAnomenFlirtTalkTimer","GLOBAL",1000)
		SetGlobal("CmT_NinaAnomenFlirtTalk","GLOBAL",4)
END

IF
	RealGlobalTimerExpired("CmT_NinaAnomenFlirtTalkTimer","GLOBAL")
	Global("CmT_NinaAnomenFlirtTalk","GLOBAL",4)
	ActionListEmpty()
	!ActuallyInCombat()
	!Detect([ENEMY])
	InParty("Anomen")
	!StateCheck("Anomen",CD_STATE_NOTVALID)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See("Anomen")
THEN
	RESPONSE #100
		SetGlobal("CmT_NinaAnomenFlirtTalk","GLOBAL",5)
END

IF
	RealGlobalTimerExpired("CmT_NinaAnomenFlirtTalkTimer","GLOBAL")
	Global("CmT_NinaAnomenFlirtTalk","GLOBAL",5)
	ActionListEmpty()
	!ActuallyInCombat()
	!Detect([ENEMY])
	InParty("Anomen")
	!StateCheck("Anomen",CD_STATE_NOTVALID)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See("Anomen")
THEN
	RESPONSE #100
		MoveToObject("Anomen")
		Interact("Anomen")
END

// 2nd Nina flirt
IF
	Global("CmT_NinaAnomenFlirtTalk","GLOBAL",6)
	InParty(Myself)
	InParty("Anomen")
THEN
	RESPONSE #100
		RealSetGlobalTimer("CmT_NinaAnomenFlirtTalkTimer","GLOBAL",1000)
		SetGlobal("CmT_NinaAnomenFlirtTalk","GLOBAL",7)
END

IF
	RealGlobalTimerExpired("CmT_NinaAnomenFlirtTalkTimer","GLOBAL")
	Global("CmT_NinaAnomenFlirtTalk","GLOBAL",7)
	ActionListEmpty()
	!ActuallyInCombat()
	!Detect([ENEMY])
	InParty("Anomen")
	!StateCheck("Anomen",CD_STATE_NOTVALID)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See("Anomen")
THEN
	RESPONSE #100
		SetGlobal("CmT_NinaAnomenFlirtTalk","GLOBAL",8)
END

IF
	RealGlobalTimerExpired("CmT_NinaAnomenFlirtTalkTimer","GLOBAL")
    Global("CmT_NinaAnomenFlirtTalk","GLOBAL",8)
	ActionListEmpty()
	!ActuallyInCombat()
	!Detect([ENEMY])
	InParty("Anomen")
	!StateCheck("Anomen",CD_STATE_NOTVALID)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See("Anomen")
THEN
	RESPONSE #100
		MoveToObject("Anomen")
		Interact("Anomen")
END

// Anomen is not a knight first check. Romance kill

IF
	Global("AnomenIsNotKnight","GLOBAL",1)
	Global("CmT_NinaAnomenKnightTalk2","GLOBAL",0)
	InParty(Myself)
	InParty("Anomen")
THEN
	RESPONSE #100
		RealSetGlobalTimer("CmT_NinaAnomenNotKnightTalkTimer","GLOBAL",300)
		SetGlobal("CmT_NinaAnomenKnightTalk2","GLOBAL",1)
END

IF
	RealGlobalTimerExpired("CmT_NinaAnomenNotKnightTalkTimer","GLOBAL")
	Global("CmT_NinaAnomenKnightTalk2","GLOBAL",1)
	ActionListEmpty()
	!ActuallyInCombat()
	!Detect([ENEMY])
	InParty("Anomen")
	!StateCheck("Anomen",CD_STATE_NOTVALID)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See("Anomen")
THEN
	RESPONSE #100
		SetGlobal("CmT_NinaAnomenKnightTalk2","GLOBAL",2)
END

IF
	RealGlobalTimerExpired("CmT_NinaAnomenNotKnightTalkTimer","GLOBAL")
	Global("CmT_NinaAnomenKnightTalk2","GLOBAL",2)
	ActionListEmpty()
	!ActuallyInCombat()
	!Detect([ENEMY])
	InParty("Anomen")
	!StateCheck("Anomen",CD_STATE_NOTVALID)
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See("Anomen")
THEN
	RESPONSE #100
		MoveToObject("Anomen")
		Interact("Anomen")
END

// Background information

IF
	AreaCheck("AR2100")
	Global("NinaBackground","GLOBAL",1) // From CMNINAFJ.D
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(Player1)
THEN
	RESPONSE #100
//		IncrementGlobal("NinaBackground","GLOBAL",1) // Removed set in BCMNINAF.D
		Interact(Player1)
END

IF
	RealGlobalTimerExpired("NinaElhanTime","GLOBAL")
	Global("NinaKnowsElhan","GLOBAL",1)
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(Player1)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1) //  From Interact
END

IF
	AreaCheck("AR2800")
	Global("NinaHomeAttack","GLOBAL",0)
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(Player1)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1) //  From Interact
END

IF
	AreaCheck("AR2807")
	Global("NinaDragon1","GLOBAL",0)
	Dead("dragblac")
	// StateCheck("dragblac",STATE_REALLY_DEAD)
	!ActuallyInCombat()
	!See([ENEMY])
	!StateCheck(Player1,CD_STATE_NOTVALID) 
	InParty(Myself)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(Player1)
THEN
	RESPONSE #100
		StartDialogNoSet(Player1) //  From Interact
END

